<?php

/**
 * ShopEx licence
 *
 * @copyright  Copyright (c) 2005-2010 ShopEx Technologies Inc. (http://www.shopex.cn)
 * @license  http://ecos.shopex.cn/ ShopEx License
 */

$db['settlement'] = array(
    'columns' => array(
        'settlement_no' => array(
            'type' => 'varchar(15)',
            'required' => true,
            'pkey' => true,
            'label' => app::get('business')->_('结算报表单号'),
            'width' => 140,
            'editable' => false,
            'searchtype' => 'has',
            'in_list' => true,
            'default_in_list' => true,
            ),
        'pre_settlement' => array(
            'type' => 'varchar(255)',
            'default' => '',
            'label' => app::get('business')->_('负结算报表'),
            'width' => 140,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'pre_settlement_cut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('负结算报表金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'pre_refund_recut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('往期售后退款总金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'b_pre_refund_recut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('往期店铺售后退款金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'p_pre_refund_recut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('往期平台售后退款金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'store_id' => array(
            'type' => 'table:storemanger@business',
            'required' => true,
            'default' => 0,
            'label' => app::get('business')->_('店铺名称'),
            'width' => 110,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'create_time' => array(
            'type' => 'time',
            'required' => true,
            'label' => app::get('business')->_('结算时间'),
            'width' => 110,
            'editable' => false,
            'in_list' => true,
            ),
        'account' => array(
            'type' => 'money',
            'label' => app::get('business')->_('店铺结算金额'),
            'default' => '0',
            'required' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'order_money' => array(
            'type' => 'money',
            'label' => app::get('business')->_('订单金额'),
            'default' => '0',
            'required' => true,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'order_cut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('平台抽成金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'order_recut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('平台承担售后退款金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'score_use' => array(
            'type' => 'money',
            'label' => app::get('business')->_('使用积分折算'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'score_give' => array(
            'type' => 'money',
            'label' => app::get('business')->_('赠送积分折算'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        're_cut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('店铺承担售后退款金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
         'total_recut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('售后退款总金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
         'refund' => array(
            'type' => 'money',
            'label' => app::get('business')->_('售前退款金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
         'is_balance' => array (
            'type' => 
              array (
                1 => '已结算',
                2 => '未结算',
                3 => '已受理',
                4 => '结算失败',
              ),
            'comment' => '是否结算',
            'editable' => false,
            'default' => '2',
            'required' => true,
         ),
        'disabled' => array(
            'type' => 'bool',
            'label' => app::get('business')->_('是否失效'),
            'default' => 'false',
            'editable' => false,
            ),
        'batch_id' => array(
            'type' => 'varchar(13)',
            'label' => app::get('business')->_('批次号'),
            'width' => 140,
            'searchtype' => 'has',
            'in_list' => true,
            'default_in_list' => true,
            ),
        ),
    'comment' => app::get('business')->_('结算单表'),
    'version' => '$Rev: 41329 $',
    );
