<?php

/**
 * ShopEx licence
 *
 * @copyright  Copyright (c) 2005-2010 ShopEx Technologies Inc. (http://www.shopex.cn)
 * @license  http://ecos.shopex.cn/ ShopEx License
 */

$db['settlement_item'] = array(
    'columns' => array(
        'id' => array(
            'type' => 'bigint unsigned',
            'required' => true,
            'pkey' => true,
            'extra' => 'auto_increment',
            'label' => app::get('business')->_('ID'),
            'width' => 110,
            'editable' => false,
            'in_list' => false,
            'hidden' => true,
            'default_in_list' => false,
            ),
        'settlement_no' => array(
            'type' => 'varchar(15)',
            'required' => true,
            'label' => app::get('business')->_('结算单号'),
            'width' => 140,
            'editable' => false,
            'searchtype' => 'has',
            'in_list' => true,
            'default_in_list' => true,
            ),
        'order_id' => array(
            'type' => 'varchar(20)',
            'label' => app::get('business')->_('单据号'),
            'width' => 200,
            'editable' => false,
            'in_list' => false,
            ),
        'account' => array(
            'type' => 'money',
            'label' => app::get('business')->_('结算金额'),
            'default' => '0',
            'required' => true,
            'filtertype' => 'number',
            'filterdefault' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'order_money' => array(
            'type' => 'money',
            'label' => app::get('business')->_('订单金额'),
            'default' => '0',
            'required' => true,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'order_cut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('订单抽成'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'order_recut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('平台承担售后退款金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'score_use' => array(
            'type' => 'money',
            'label' => app::get('business')->_('使用积分折算金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'score_give' => array(
            'type' => 'money',
            'label' => app::get('business')->_('赠送积分折算金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'is_refund' => array(
            'type' => array(
                '0' => app::get('business')->_('未发生退款'),
                '1' => app::get('business')->_('发生退款'),
                ),
            'label' => app::get('business')->_('是否退款'),
            'width' => 110,
            'default' => '0',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        're_cut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('店铺售后退款金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'total_recut' => array(
            'type' => 'money',
            'label' => app::get('business')->_('售后退款总金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'refund' => array(
            'type' => 'money',
            'label' => app::get('business')->_('售前退款金额'),
            'default' => '0',
            'required' => true,
            'width' => 130,
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'refund_id' => array(
            'type' => 'varchar(300)',
            'label' => app::get('business')->_('售后退款单'),
            'width' => 200,
            'editable' => false,
            'in_list' => false,
            ),
        'item_type' => array(
            'type' => array(
                'order' => app::get('business')->_('订单结算明细'),
                'refund' => app::get('business')->_('往期售后结算明细'),
                ),
            'label' => app::get('business')->_('明细类型'),
            'width' => 110,
            'default' => 'order',
            'editable' => false,
            'in_list' => true,
            'default_in_list' => true,
            ),
        'disabled' => array(
            'type' => 'bool',
            'default' => 'false',
            'editable' => false,
            ),
        ),
    'comment' => app::get('financial')->_('结算明细'),
    'version' => '$Rev: 41329 $',
    );
